services:
 cache:
  image: redis:alpine
  ports:
    - 6379:6379
  volumes:
    - cache:/var/lib/redis

 database:
  image: mysql
  ports:
   - 52000:3306
  environment:
    MYSQL_ROOT_PASSWORD: helloworld1234()
    MYSQL_DATABASE: Shop
  volumes:
   - database:/var/lib/mysql

 crawler:
  build: ./src
  depends_on:
   - cache
  links:
   - cache


 consumer:
  build: ./background
  depends_on:
   - cache
   - database
  links:
   - cache
   - database

  

volumes:
 cache:
 database:
    


# volumes:
#   tenorCrawl
